version: '3.4'

services:
  docuchat:
    image: docuchat
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        USER_NAME: ${USER_NAME:-appuser}
    ports:
      - "8501:8501"        
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./data:/data
      