version: '3.4'

services:
  docuchat:
    image: docuchat
    container_name: python_docuchat 
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        USER_NAME: ${USER_NAME:-appuser}
        CHUNKER_NLP_MODEL_OPTIONS: ${CHUNKER_NLP_MODEL_OPTIONS}
    environment:
      - TZ=${TIMEZONE:-Europe/Amsterdam}    
      - RUNNING_IN_DOCKER=true        
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_docuchat
    command: ['--default-authentication-plugin=caching_sha2_password']
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./db-data/mysql:/var/lib/mysql

  milvus-standalone:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus-standalone_docuchat
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - ./db-data/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    command: ["milvus", "run", "standalone"]