version: '3.4'

services:
  docuchat:
    image: docuchat
    container_name: python_docuchat 
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        USER_NAME: ${USER_NAME:-appuser}
        CHUNKER_NLP_MODEL_OPTIONS: ${CHUNKER_NLP_MODEL_OPTIONS}
    environment:
      - TZ=${TIMEZONE:-Europe/Amsterdam}    
      - RUNNING_IN_DOCKER=true        
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_docuchat
    command: ['--default-authentication-plugin=caching_sha2_password']
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'      
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./db-data:/var/lib/mysql

  milvus:
    image: milvusdb/milvus:2.3-latest
    container_name: milvus_server_docuchat
    ports:
      - "19530:19530"
    volumes:
      - ./milvus/db:/var/lib/milvus/db
      - ./milvus/conf:/var/lib/milvus/conf
      - ./milvus/logs:/var/lib/milvus/logs
    environment:
      MINIO_ADDRESS: minio:9000
    depends_on:
      - minio
      - etcd

  minio:
    image: minio/minio
    container_name: minio_docuchat
    volumes:
      - ./milvus/minio:/data
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd_docuchat
    environment:
      ALLOW_NONE_AUTHENTICATION: 'yes'
    volumes:
      - ./milvus/etcd:/etcd_data
