"""Extracted.name and domain_id is now unique

Revision ID: b72c26e2d17f
Revises: d0090ad818e3
Create Date: 2024-02-20 00:31:00.432446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72c26e2d17f'
down_revision: Union[str, None] = 'd0090ad818e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='extracted_texts')
    op.create_unique_constraint('_name_domain_id_uc', 'extracted_texts', ['name', 'domain_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_domain_id_uc', 'extracted_texts', type_='unique')
    op.create_index('name', 'extracted_texts', ['name'], unique=True)
    # ### end Alembic commands ###
