"""Index embeddings

Revision ID: bbdf2a5bb233
Revises: 4b8effd720c9
Create Date: 2024-03-05 02:31:28.562797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdf2a5bb233'
down_revision: Union[str, None] = '4b8effd720c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_embeddings_chunk_id', 'embeddings', ['chunk_id'], unique=False)
    op.create_index('ix_embeddings_embedding_process_id', 'embeddings', ['embedding_process_id'], unique=False)
    op.create_unique_constraint('uix_chunk_id_embedding_process_id', 'embeddings', ['chunk_id', 'embedding_process_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_chunk_id_embedding_process_id', 'embeddings', type_='unique')
    op.drop_index('ix_embeddings_embedding_process_id', table_name='embeddings')
    op.drop_index('ix_embeddings_chunk_id', table_name='embeddings')
    # ### end Alembic commands ###
