"""ModelCache

Revision ID: cdf9b87e5fb0
Revises: a6b921bda541
Create Date: 2024-03-19 01:08:10.810006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cdf9b87e5fb0'
down_revision: Union[str, None] = 'a6b921bda541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('Groq', 'OpenAI', name='modelsource'), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('attributes', mysql.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'model_id', name='_source_model_id_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_cache')
    # ### end Alembic commands ###
