[server]
runOnSave = true
maxUploadSize = 1000

[client]
showSidebarNavigation = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#EA5455"
backgroundColor = "#F9F5EB"
secondaryBackgroundColor = "#E4DCCF"
textColor = "#002B5B" 
font = "sans serif"

[logger]
level = "warning"