[server]
runOnSave = true
maxUploadSize = 500
[browser]
gatherUsageStats = false
[theme]
primaryColor = "#3178C6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"